package gui;

import ca.CA;
import java.awt.Color;
import java.awt.Dimension;
import java.util.Random;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JSlider;
import javax.swing.JToggleButton;

/**
 *
 * @author tadaki
 */
public class CAMain extends javax.swing.JFrame {

    private int rule = 90;
    private double r = 0.5;
    private final int numCell = 200;
    private final CA ca;
    private final DrawPanel drawPanel;
    private JToggleButton startStop;
    private JCheckBox checkSingleSite;
    private JComboBox<Integer> ruleSelect;
    private JSlider selectR;
    private boolean singleSite = false;
    private final Dimension panelSize = new Dimension(800, 800);

    /**
     * Creates new form Main
     */
    public CAMain() {
        initComponents();
        ca = new CA(numCell, rule, new Random(48L));
        ca.initialize(r);

        drawPanel = new DrawPanel();
        drawPanel.setPreferredSize(panelSize);
        drawPanel.setBackground(Color.WHITE);
        drawPanel.initialize(ca);
        getContentPane().add(drawPanel, java.awt.BorderLayout.CENTER);
        initComponent2();
        pack();
    }

    /**
     * menuBarへのコンポーネント追加
     */
    private void initComponent2() {
        startStop = new JToggleButton();
        startStop.setText("START");
        startStop.addActionListener(e -> startStopAction());
        menuBar.add(startStop);

        checkSingleSite = new JCheckBox();
        checkSingleSite.setText("Single Site");
        checkSingleSite.addActionListener(e -> caInitialize());
        menuBar.add(checkSingleSite);

        menuBar.add(new JLabel(" rule: "));
        singleSite = checkSingleSite.isSelected();
        ruleSelect = new JComboBox<>();
        for (int k = 1; k < 255; k++) {
            ruleSelect.addItem(k);
        }
        ruleSelect.addActionListener(e -> ruleSelectActionPerformed());
        menuBar.add(ruleSelect);
        ruleSelect.setSelectedItem(rule);

        selectR = new JSlider();
        selectR.setMaximum(100);
        selectR.addChangeListener(e -> selectRActionPerformed());
        menuBar.add(selectR);

    }

    private void ruleSelectActionPerformed() {
        if (drawPanel == null) {
            return;
        }
        rule = (Integer) ruleSelect.getSelectedItem();
        drawPanel.stop();
        ca.setRule(rule);
        caInitialize();
    }

    private void selectRActionPerformed() {
        if (drawPanel == null) {
            return;
        }
        int m = selectR.getMaximum();
        int rr = selectR.getValue();
        r = (double) rr / m;
        drawPanel.stop();
        caInitialize();
    }

    private void startStopAction() {
        if (drawPanel == null) {
            return;
        }
        if (drawPanel.isRunning()) {
            drawPanel.stop();
            startStop.setText("START");
        } else {
            caInitialize();
            drawPanel.start();
            new Thread(drawPanel).start();
            startStop.setText("Stop");
        }
    }

    private void caInitialize() {
        singleSite = checkSingleSite.isSelected();
        if (singleSite) {
            ca.initialSingle();
        } else {
            ca.initialize(r);
        }
        drawPanel.initialize(ca);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        quit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuBar.setBackground(new java.awt.Color(255, 255, 204));

        fileMenu.setText("File");

        quit.setText("quit");
        quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitActionPerformed(evt);
            }
        });
        fileMenu.add(quit);

        menuBar.add(fileMenu);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_quitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CAMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CAMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CAMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CAMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new CAMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem quit;
    // End of variables declaration//GEN-END:variables
}
