package gui;

import ca.CA;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Point;
import java.awt.geom.Point2D;
import java.awt.geom.Rectangle2D;
import java.awt.image.BufferedImage;

/**
 *
 * @author tadaki
 */
public class DrawPanel extends javax.swing.JPanel implements Runnable {

    protected Dimension dimension;
    protected BufferedImage image;
    protected Point offset = new Point(50, 50);
    protected int sleep = 100;
    protected Point2D.Double f;
    protected volatile boolean running = false;

    private CA ca;
    private int tmax;
    private int xmax;
    private int t = 0;

    /**
     * Creates new form DrawPanel2
     */
    public DrawPanel() {
        initComponents();
    }

    /**
     * CAを指定してJPanelを初期化
     *
     * @param ca
     */
    public void initialize(CA ca) {
        this.ca = ca;
        xmax = ca.getN();
        tmax = xmax;
        initializeSub();
        sleep = 100;
        t = 0;
    }

    private void initializeSub() {
        initializePanel();
        if (image != null) {
            clearImage();
            dimension = this.getPreferredSize();
            double fy = (dimension.height - offset.y) / tmax;
            double fx = (dimension.width - 2 * offset.x) / xmax;
            f = new Point2D.Double(fx, fy);
        }
        clearImage();
    }

    public void initializePanel() {
        dimension = this.getPreferredSize();
        image = new BufferedImage(dimension.width, dimension.height,
                BufferedImage.TYPE_INT_RGB);
        clearImage();
    }

    @Override
    public void paintComponent(Graphics g) {
        if (image == null) {
            clearImage();
        }
        g.drawImage(image, 0, 0, this);
    }

    public void clearImage() {
        if (image == null) {
            return;
        }
        Graphics g = image.getGraphics();
        g.setColor(this.getBackground());
        g.fillRect(0, 0, image.getWidth(), image.getHeight());
    }

    public void mkImage() {
        int cells[] = ca.getCells();
        Graphics2D g = (Graphics2D) image.getGraphics();
        g.setColor(Color.RED);
        for (int i = 0; i < cells.length; i++) {
            int c = cells[i];
            switch (c) {
                case 1 -> {
                    Rectangle2D.Double r = new Rectangle2D.Double(
                            offset.x + f.x * i, offset.y + f.y * t, f.x, f.y);
                    g.fill(r);
                }
                default -> {
                }
            }
        }
    }

    @Override
    public void run() {
        while (running) {
            mkImage();
            repaint();
            t++;
            ca.update();
            if (t % tmax == 0) {
                t = 0;
                clearImage();
            }
            try {
                Thread.sleep(sleep);
            } catch (InterruptedException ex) {
            }
        }
    }

    public void start() {
        running = true;
    }

    public void stop() {
        running = false;
    }

    public boolean isRunning() {
        return running;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
